language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm

env:
  - SYMFONY_VERSION=2.7.*

matrix:
  include:
    - php: 5.6
      env: SYMFONY_VERSION=2.0.*
    - php: 5.6
      env: SYMFONY_VERSION=2.1.*
    - php: 5.6
      env: SYMFONY_VERSION=2.2.*
    - php: 5.6
      env: SYMFONY_VERSION=2.3.*
    - php: 5.6
      env: SYMFONY_VERSION=2.4.*
    - php: 5.6
      env: SYMFONY_VERSION=2.5.*
    - php: 5.6
      env: SYMFONY_VERSION=2.7.*
    - php: 5.6
      env: SYMFONY_VERSION=2.8.*@dev
    - php: 5.6
      env: SYMFONY_VERSION=3.0.*@dev
    - php: 5.6
      env: SYMFONY_VERSION=2.0.* COMPOSER_FLAGS="--prefer-lowest"

before_install:
  - composer self-update
  - composer require symfony/symfony:${SYMFONY_VERSION} --no-update

install: composer update --prefer-source $COMPOSER_FLAGS

script: phpunit --coverage-text

notifications:
  slack: liip:3QOs1QKt3aCFxpJvRzpJCbVZ
