language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  - SYMFONY_VERSION=2.7.*

matrix:
  include:
    - php: 5.6
      env: SYMFONY_VERSION=2.8.*@dev
    - php: 5.6
      env: SYMFONY_VERSION=3.3.*@dev
    - php: 5.6
      env: SYMFONY_VERSION=3.4.*@dev
    - php: 7.2
      env: SYMFONY_VERSION=4.0.*@dev
    - php: 5.6
      env: COMPOSER_FLAGS="--prefer-lowest"

before_install:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install: composer update --prefer-source $COMPOSER_FLAGS

script: ./vendor/bin/phpunit --coverage-text

notifications:
  slack: liip:3QOs1QKt3aCFxpJvRzpJCbVZ
